# -*- coding: utf-8 -*-
"""esferaSoft.AssignmentTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMONAZC2X2wvNeQvCVdYNIDpYpmBDhCK
"""

import pandas as pd
import numpy as np
from datetime import timedelta

np.random.seed(42)
dates=pd.date_range(end=pd.Timestamp.today(),periods=90)
stores=[1,2,3] #these are the mock list of stores
data=[]

for store in stores:
  sales=np.random.randint(1000, 5000, size=90).astype(float)
  missing_idx=np.random.choice(90, 10, replace=False)
  sales[missing_idx]=np.nan
  for i in range(90):
    data.append([store, dates[i], sales[i]])

df=pd.DataFrame(data, columns=['store_id', 'date', 'total_sales'])
df['total_sales']=df.groupby('store_id')['total_sales'].transform(lambda x: x.interpolate())

forecast=[]
for store in df['store_id'].unique():
  store_data=df[df['store_id']==store].sort_values('date')
  last_date=store_data['date'].max()
  recent_sales=store_data['total_sales'].tail(7).mean()

  for i in range(1,8):
    forecast.append([store, last_date+timedelta(days=i), recent_sales])

forecast_df=pd.DataFrame(forecast, columns=['store_id', 'date', 'forecast_sales'])
print(forecast_df)

#OUTPUT BELOW